### ISSUE TITLE
How do you check if the payment was actually made?

### ISSUE THREAD

**Issue by Mrfuyu** [testdrivenio/django-stripe-checkout#1]
If the purchased content is available on the success page or the view on the success page sets the status to payed, then there's a simple case how the user can fake it's payment.

The user can see in the browsers console what's the redirect to the success page and simply could copy that URL an browse to it.

How do you check automatically if the payment was actually made?

**Comment by mjhea0** [comment]
This should help https://stripe.com/docs/payments/checkout/accept-a-payment#payment-success

**Comment by duplxey** [comment]
I think this confirmation should be included at the end of the tutorial or at least linked, because I've stumbled across the same problem.

**Comment by mjhea0** [comment]
Do you think it would be helpful to show how to set up the web hook in the post?

**Comment by duplxey** [comment]
The post is really well written, but this confirmation/webhook part is missing. I've managed to get it working, but I spent quite some time on it. I think adding it to the tutorial would save many developers a lot of time & unnecesary headaches.

If you want I can open a pull request with my solution.

**Comment by mjhea0** [comment]
Please do. I'd love to see your code along with your workflow (are you waiting to get confirmation from web hook back before giving the end user access to the service?).

For what it's worth, I did have a team at Stripe review the post before I released it and they gave it the green light.

**Comment by duplxey** [comment]
I more or less followed Stripe's tutorial. I give the end user access to my service once `checkout.session.completed` webhook is called. For user identification I initialize checkout_session with a `client_reference_id` which matches Django's user ID. I can then fetch `client_reference_id` and `payment_intent` from webhook and make changes to my models.

**Comment by mjhea0** [comment]
What do you display in the success redirect page then?

If you were selling a tangible product like a shirt or coffee beans, I think it's fine to indicate that the purchase was successful and then wait to ship out the product until you get confirmation from the webhook.

However, if it's a SaaS service, buyers typically expect immediate access. So, I'm curious how you handle the interim period between the success redirect and actually providing the user access. Do you just not send out the login or access credentials until the hook comes back?

**Comment by duplxey** [comment]
That's right. I'm working on a SaaS service so I immediately display the success page, but make changes to my models once I get the confirmation from the webhook.

If I'm not mistaken Stripe also delays the checkout for like 10 seconds when using webhooks so providing the end user access to the service is more or less immediate.

I'm going to open a pull request in like 15 minutes so you can check out my code.
