### ISSUE TITLE
Is it necessary to make client side request for stripe publishable key?

### ISSUE THREAD

**Issue by banagale** [testdrivenio/django-stripe-checkout#13]
In this non-Elements example of Stripe Checkout, is it necessary to create an endpoint to return the publishable key?

Since this key is not dynamic couldn't this key just be included in the context of the page showing the checkout button?

Perhaps this endpoint makes it so checkout buttons can be used in any template that includes the Javascript, thus not requiring the extra step of passing in the key in context?

**Comment by mjhea0** [comment]
Yes, you can include it in the request context.
